### ISSUE TITLE
Github page 404 error

### ISSUE THREAD

**Issue by amjadnoor** [jkugsiya/Melbourne#5]
This repo [Github page](https://jkugsiya.github.io/Melbourne/) is active but they give 404 error becase of main html file not in the root directory. Please change the main index.html file to the root directory so the [Github page](https://jkugsiya.github.io/Melbourne/) will be ready.

**Comment by jkugsiya** [comment]
> This repo [Github page](https://jkugsiya.github.io/Melbourne/) is active but they give 404 error becase of main html file not in the root directory. Please change the main index.html file to the root directory so the [Github page](https://jkugsiya.github.io/Melbourne/) will be ready.

There are 3 different versions of the website in this repo, so please access the page by accessing jkugsiya.github.io/Melbourne/Melbourne-X where X represents the version that is 1, 2, and 3.
for ex: [https://jkugsiya.github.io/Melbourne/Melbourne-2](https://jkugsiya.github.io/Melbourne/Melbourne-2)
